name: 'sales_semantic_models'
version: '1.0.0'
config-version: 2

profile: 'sales_semantic_models'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

flags:
  source_freshness_run_project_hooks: True

vars:
  data_quality_enabled: true
  version_prefix: 'v1_0_0'

sources:
  +tags: ['sales', 'sales_semantic_models']

models:
  +persist_docs:
    relation: true
    columns: true

  +tags: ['sales', 'sales_semantic_models']

  sales_semantic_models:
    transform:
      +enabled: true
      +materialized: ephemeral
      +database: WH_NBE_SalesSemantic_POC
      +schema: sales_transform

    publish:
      +enabled: true
      +materialized: table
      +database: WH_NBE_SalesSemantic_POC
      shared:
        +schema: sales_shared
      private:
        +schema: sales_private

    metrics:
      +enabled: true

seeds:
  +tags: ['sales', 'sales_semantic_models', 'seeds']
  +persist_docs:
    relation: true
    columns: true
  sales_semantic_models:
    +enabled: true
    +database: WH_NBE_SalesSemantic_POC
    +schema: sales_transform
    +full_refresh: true

tests:
  +store_failures: true
  +schema: "sales_test_log"
  +tags: ['sales', 'sales_semantic_models']
